### ISSUE TITLE
Duplicate compat entry

### ISSUE THREAD

**Issue by christopher-dG** [theogf/AugmentedGaussianProcesses.jl#33]
https://github.com/theogf/AugmentedGaussianProcesses.jl/blob/5f20b0b3bc781cbbf655980269f37b9110b670b6/Project.toml#L42-L43

Found by https://github.com/JuliaRegistries/TagBot/issues/76

**Comment by theogf** [comment]
Solved by https://github.com/theogf/AugmentedGaussianProcesses.jl/commit/03f121bbe1dea48e83b06fe270a64e01190d80e5
